name: Build test frontend
description: Builds the test frontend, and caches the next.js cache directory
inputs:
   ALGOLIA_API_KEY:
      description: 'Algolia api key'
      required: true
   NEXT_PUBLIC_DEV_API_AUTH_TOKEN:
      description: 'Dev api auth token'
      required: true

runs:
   using: 'composite'
   steps:
      - name: Cache Next.js cache directory
        uses: actions/cache@v3
        with:
           path: frontend/.next/cache
           key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
           restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build Next.js
        env:
           NODE_ENV: test
           ALGOLIA_API_KEY: ${{ inputs.ALGOLIA_API_KEY }}
           NEXT_PUBLIC_DEV_API_AUTH_TOKEN: ${{ inputs.NEXT_PUBLIC_DEV_API_AUTH_TOKEN }}
        run: cd frontend && pnpm build
        shell: bash
